package fi.oulu.elsa.domain.enumeration

/**
 * The CanmedsRooli enumeration.
 */
enum class CanmedsRooli {
    AMMATILLISUUS, VUOROVAIKUTUSTAIDOT, YHTEISTYOTAIDOT, JOHTAMISTAIDOT, TERVEYDEN_JA_HYVINVOINNIN_EDISTAMINEN,
    OMA_OSAAMINEN_JA_TIEDONHALLINTA, LAAKETIETEELLINEN_OSAAMINEN
}
