style:
  MaxLineLength:
    maxLineLength: 180
  WildcardImport:
    active: false
  NewLineAtEndOfFile:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
naming:
  ConstructorParameterNaming:
    active: false
complexity:
  TooManyFunctions:
    thresholdInClasses: 20
    thresholdInInterfaces: 16
  LongParameterList:
    constructorThreshold: 17
    functionThreshold: 10
  LongMethod:
    threshold: 71
  LargeClass:
    threshold: 1000
  ComplexCondition:
    threshold: 5
  NestedBlockDepth:
    active: false
exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
performance:
  SpreadOperator:
    active: false
