style:
  MaxLineLength:
    maxLineLength: 180
  UnusedVariable:
    active: true
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
naming:
  ConstructorParameterNaming:
    active: false
complexity:
  TooManyFunctions:
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 16
  LongParameterList:
    allowedConstructorParameters: 17
    allowedFunctionParameters: 10
  ComplexCondition:
    allowedConditions: 5
  CyclomaticComplexMethod:
    allowedComplexity: 15
  NestedBlockDepth:
    active: false
exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
performance:
  SpreadOperator:
    active: false
