---
services:

  db:
    image: postgres:16.9
    init: true
    restart: always
    networks:
      - elsa
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=elsaBackend
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  elsa-frontend:
    image: 939452229770.dkr.ecr.eu-west-1.amazonaws.com/ecr-dev-frontend:latest
    networks:
      - elsa
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://elsa-backend:8080
    depends_on:
      elsa-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  elsa-backend:
    image: 654795471143.dkr.ecr.eu-west-1.amazonaws.com/ecr-shared-backend:feature-a32b951f
    restart: on-failure
    networks:
      - elsa
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=elsaBackend
      - SPRING_PROFILES_ACTIVE=dev
      - POSTGRES_PASSWORD=
      - APPLICATION_SECURITY_ENCODED_KEY
    ports:
      - 9080:8080
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/management/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

networks:
  elsa:
