package fi.elsapalvelu.elsa.service

import com.itextpdf.io.font.FontProgram
import com.itextpdf.io.font.FontProgramFactory
import fi.elsapalvelu.elsa.service.valmistuminen.PdfService
import org.springframework.beans.factory.annotation.Value
import org.springframework.core.io.Resource
import org.springframework.stereotype.Component

data class UnsupportedPdfCharacter(
    val value: String,
    val codePoint: String
) {
    override fun toString(): String = "$value ($codePoint)"
}

/**
 * Checks text against the fonts embedded in PDFs generated by [PdfService].
 */
@Component
class PdfTextValidator(
    @Value("classpath:fonts/LiberationSerif-Bold.ttf")
    private val liberationSerifFontBold: Resource,
    @Value("classpath:fonts/LiberationSerif-Regular.ttf")
    private val liberationSerifFont: Resource,
    @Value("classpath:fonts/NotoSans-Italic.ttf")
    private val notoSansFontItalic: Resource,
    @Value("classpath:fonts/NotoSans-Regular.ttf")
    private val notoSansFont: Resource
) {
    private val fontPrograms: List<FontProgram> by lazy {
        listOf(
            liberationSerifFontBold,
            liberationSerifFont,
            notoSansFontItalic,
            notoSansFont
        ).map { resource ->
            resource.inputStream.use { FontProgramFactory.createFont(it.readBytes()) }
        }
    }

    fun findUnsupportedCharacters(text: String?): List<UnsupportedPdfCharacter> {
        if (text.isNullOrEmpty()) {
            return emptyList()
        }

        val unsupportedCodePoints = linkedSetOf<Int>()
        text.codePoints().forEach { codePoint ->
            if (codePoint !in NON_RENDERED_WHITESPACE &&
                fontPrograms.none { it.getGlyph(codePoint) != null }
            ) {
                unsupportedCodePoints.add(codePoint)
            }
        }

        return unsupportedCodePoints.map { codePoint ->
            UnsupportedPdfCharacter(
                value = String(Character.toChars(codePoint)),
                codePoint = "U+${codePoint.toString(16).uppercase().padStart(4, '0')}"
            )
        }
    }

    private companion object {
        val NON_RENDERED_WHITESPACE = setOf('\t'.code, '\n'.code, '\r'.code)
    }
}
