package fi.elsapalvelu.elsa.service.dto.enumeration

enum class ValmistumispyynnonTila {
    UUSI,
    ODOTTAA_VASTUUHENKILON_TARKASTUSTA,
    VASTUUHENKILON_TARKASTUS_PALAUTETTU,
    ODOTTAA_VIRKAILIJAN_TARKASTUSTA,
    VIRKAILIJAN_TARKASTUS_KESKEN,
    VIRKAILIJAN_TARKASTUS_PALAUTETTU,
    ODOTTAA_VASTUUHENKILON_HYVAKSYNTAA,
    VASTUUHENKILON_HYVAKSYNTA_PALAUTETTU,
    HYVAKSYTTY
}
