package fi.elsapalvelu.elsa.security

const val ADMIN: String = "ROLE_ADMIN"
const val USER: String = "ROLE_USER"
const val ANONYMOUS: String = "ROLE_ANONYMOUS"

// ELSA-palvelun käyttäjäroolit
const val ERIKOISTUVA_LAAKARI: String = "ROLE_ERIKOISTUVA_LAAKARI"
const val LAHIKOULUTTAJA: String = "ROLE_LAHIKOULUTTAJA"
const val KOULUTTAJA: String = "ROLE_KOULUTTAJA"
const val VASTUUHENKILO: String = "ROLE_VASTUUHENKILO"
const val KOULUTUSDEKAANI: String = "ROLE_KOULUTUSDEKAANI"
const val PALVELUJARJESTELMAN_VIRKAILIJA: String = "ROLE_PALVELUJARJESTELMAN_VIRKAILIJA"
const val OPINTOHALLINNON_VIRKAILIJA: String = "ROLE_OPINTOHALLINNON_VIRKAILIJA"
const val PAAKAYTTAJA: String = "ROLE_PAAKAYTTAJA"
const val TEKNINEN_PAAKAYTTAJA: String = "ROLE_TEKNINEN_PAAKAYTTAJA"

const val ERIKOISTUVA_LAAKARI_IMPERSONATED: String = "ROLE_ERIKOISTUVA_LAAKARI_IMPERSONATED"
