package fi.elsapalvelu.elsa.domain.enumeration

enum class ArviointiasteikonTasoTyyppi {

    // EPA
    OHJAAJAN_TOIMINNAN_SEURAAMINEN,
    TOIMINTA_SUORAN_OHJAUKSEN_ALAISENA,
    TOIMINTA_EPASUORAN_OHJAUKSEN_ALAISENA,
    TOIMINTA_ILMAN_OHJAUSTA,
    TOIMINTA_OHJAAJANA,

    // ETAPPI
    TULOKAS,
    ALKUVAIHEEN_ERIKOISTUJA,
    EDISTYNYT_ERIKOISTUJA,
    ERIKOISLAAKARI,
    ERITYINEN_OSAAMINEN
}
