package fi.elsapalvelu.elsa.domain.enumeration

enum class AvoinAsiaTyyppiEnum {
    KOULUTUSSOPIMUS,
    ALOITUSKESKUSTELU,
    VALIARVIOINTI,
    KEHITTAMISTOIMENPITEET,
    LOPPUKESKUSTELU,
    VASTUUHENKILON_ARVIO,
    SEURANTAJAKSO,
    TERVEYSKESKUSKOULUTUSJAKSO,
    VALMISTUMISPYYNTO,
    KOULUTTAJAVALTUUTUS
}
