package fi.elsapalvelu.elsa.domain.enumeration

enum class OpintosuoritusTyyppiEnum {
    JOHTAMISOPINTO,
    SATEILYSUOJAKOULUTUS,
    VALTAKUNNALLINEN_KUULUSTELU,
    KOEJAKSO,
    TERVEYSKESKUSKOULUTUSJAKSO,
    YLEISLAAKETIETEEN_ERITYISKOULUTUS,
    MUUT_OPINNOT,
    YEK_TERVEYSKESKUSKOULUTUSJAKSO,
    YEK_TEORIAKOULUTUS,
    YEK_PATEVYYS
}
