package fi.elsapalvelu.elsa.domain.enumeration

enum class OpintosuoritusTyyppiEnum {
    JOHTAMISOPINTO,
    SATEILYSUOJAKOULUTUS,
    VALTAKUNNALLINEN_KUULUSTELU,
    KOEJAKSO,
    TERVEYSKESKUSKOULUTUSJAKSO,
    YLEISLAAKETIETEEN_ERITYISKOULUTUS
}
