package fi.elsapalvelu.elsa.domain.enumeration

enum class VastuuhenkilonTehtavatyyppiEnum {
    KOEJAKSOSOPIMUSTEN_JA_KOEJAKSOJEN_HYVAKSYMINEN,
    TERVEYSKESKUSKOULUTUSJAKSOJEN_HYVAKSYMINEN,
    VALMISTUMISPYYNNON_OSAAMISEN_ARVIOINTI,
    VALMISTUMISPYYNNON_HYVAKSYNTA,
    YEK_TERVEYSKESKUSKOULUTUSJAKSO,
    YEK_VALMISTUMINEN
}
