FROM amazon/aws-for-fluent-bit:latest
ADD fluent.conf /fluent.conf
ENV SANDBOXBUCKET=elsa-sandbox-ecs-backend-bucket-logs
ENV DEVBUCKET=elsa-dev-ecs-backend-bucket-logs
ENV STAGINGBUCKET=elsa-staging-ecs-backend-bucket-logs
ENV PRODBUCKET=elsa-prod-ecs-backend-bucket-logs
