name: Dependency check

on:
  schedule:
    # daily
    - cron: "0 0 * * *"

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-includes: |
            caches
            notifications
            dependency-check-data
      - name: NVD update
        continue-on-error: true
        run: ./gradlew dependencyCheckUpdate
      - name: Dependency check
        continue-on-error: true
        run: ./gradlew dependencyCheckAnalyze
      - name: Upload dependency check report
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report.csv
          path: ./build/reports/dependency-check-report.csv
